### ISSUE TITLE
Does React-Fastclick needs Fastclick ?

### ISSUE THREAD

**Issue by aidonsnous** [moodysalem/react-fastclick#1]
Hello;
I don't get the what react-fastclick does. Thinking that it remove the 300ms delay from click event; I would like to know if  for using react-fastclick I need first fastclick and what are the browser that it supports?

**Comment by moodysalem** [comment]
You don't need fastclick on the page to use this

This is a [React](https://facebook.github.io/react/) component that you can wrap around your other React components that listens for touch start and touch end events and detects a 'tap' similar to how FastClick works, and then triggers a 'click' and/or 'focus' on the tapped element
